// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace AppCherrys
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Models;
    using CommonLib.Models.Tablon;

    /// <summary>
    /// Loggin de usuarios, servidor de anuncios, eventos, actas...
    /// </summary>
    public partial interface IClientTablon : IDisposable
    {

        IList<Anuncio> GetItems();

        Task<IList<Anuncio>> GetItemsAsync();

        void EditItem(Anuncio item = default(Anuncio));

        Task EditItemAsync(Anuncio item = default(Anuncio));

        Anuncio CreateItem(Anuncio item = default(Anuncio));

        Task<Anuncio> CreateItemAsync(Anuncio item = default(Anuncio));

        Anuncio GetItem(int id);

        Task<Anuncio> GetItemAsync(int id);

        void DeleteItem(int id);

        Task DeleteItemAsync(int id);
    }
}
