// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace KQ.Xamarin.ClientService
{
    using KQ.CommonLib.Models.Tablon;
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;

    /// <summary>
    /// Loggin de usuarios, servidor de anuncios, eventos, actas...
    /// </summary>
    public partial interface IClient<T> : IDisposable
    {

        IList<T> GetItems();

        Task<IList<T>> GetItemsAsync();

        void EditItem(T item = default(T));

        Task EditItemAsync(T item = default(T));

        Anuncio CreateItem(T item = default(T));

        Task<Anuncio> CreateItemAsync(T item = default(T));

        Anuncio GetItem(int id);

        Task<Anuncio> GetItemAsync(int id);

        void DeleteItem(int id);

        Task DeleteItemAsync(int id);
    }
}
