// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace AppCherrys.ClientService
{
    using AppCherrys.ClientService.Actas;
    using AppCherrys.ClientService.Calendario;
    using AppCherrys.ClientService.Tablon;
    using AppCherrys.ClientService.Tareas;
    using AppCherrys.ClientService.Usuarios;
    using Microsoft.Rest;
    using System;

    /// <summary>
    /// Loggin de usuarios, servidor de anuncios, eventos, actas...
    /// </summary>
    public partial class AppCherrysClient : ServiceClient<AppCherrysClient>
    {
        #region Propiedades y atributos
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        protected Uri BaseUri { get; set; }

        public ClientServiceTablon ServiceTablon { get; private set; } = null;
        public ClientServiceActa ServiceActa { get; private set; } = null;
        public ClientServiceCalendario ServiceCalendario { get; private set; } = null;
        public ClientServiceTarea ServiceTarea { get; private set; } = null;
        public ClientServiceUsuario ServiceUsuario { get; private set; } = null;

        #endregion

        #region Constructor
        private static AppCherrysClient _Clase = null;
        
        public static AppCherrysClient GetInstance()
        {
            if (_Clase == null)
                _Clase = new AppCherrysClient();

            return _Clase;
        }
        private AppCherrysClient() : base()
        {
            this.Initialize();
        }

        /// <summary>
        /// Initializes client properties.
        /// </summary>
        private void Initialize()
        {
            this.BaseUri = new Uri($"{App.AzureBackendUrl}");

            var baseUrl = this.BaseUri.AbsoluteUri;

            //pal tablon
            var urlTablon = new Uri(new Uri(baseUrl + (baseUrl.EndsWith("/") ? "" : "/")), "api/tablon").ToString();
            ServiceTablon = new ClientServiceTablon(this.HttpClient, urlTablon);

            //pa las actas
            var urlActas = new Uri(new Uri(baseUrl + (baseUrl.EndsWith("/") ? "" : "/")), "api/acta").ToString();
            ServiceActa = new ClientServiceActa(this.HttpClient, urlActas);

            //pal calendario
            var urlCalendario = new Uri(new Uri(baseUrl + (baseUrl.EndsWith("/") ? "" : "/")), "api/calendario").ToString();
            ServiceCalendario = new ClientServiceCalendario(this.HttpClient, urlCalendario);

            //pa las tareas
            var urlTareas = new Uri(new Uri(baseUrl + (baseUrl.EndsWith("/") ? "" : "/")), "api/tarea").ToString();
            ServiceTarea = new ClientServiceTarea(this.HttpClient, urlTareas);

            //pal usuario
            var urlUsuario = new Uri(new Uri(baseUrl + (baseUrl.EndsWith("/") ? "" : "/")), "api/usuario").ToString();
            ServiceUsuario = new ClientServiceUsuario(this.HttpClient, urlUsuario);
        }

        #endregion
        
    }
}
